# Generated by Django 6.0.5 on 2026-05-06 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('avaliacao', 'Avaliacao'), ('entrega', 'Entrega'), ('aula', 'Aula'), ('reuniao', 'Reuniao')], default='aula', max_length=20)),
                ('disciplina', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'evento academico',
                'verbose_name_plural': 'eventos academicos',
                'ordering': ['data', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='PostFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=120)),
                ('conteudo', models.TextField()),
                ('categoria', models.CharField(default='Geral', max_length=60)),
                ('publicado', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'post do feed',
                'verbose_name_plural': 'posts do feed',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('ano_letivo', models.PositiveIntegerField(default=2026)),
                ('periodo', models.CharField(default='Manha', max_length=40)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('matricula', models.CharField(blank=True, max_length=30)),
                ('perfil', models.CharField(choices=[('aluno', 'Aluno'), ('professor', 'Professor'), ('gestor', 'Gestor'), ('responsavel', 'Responsavel')], default='aluno', max_length=20)),
                ('turma', models.CharField(blank=True, max_length=80)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'usuario do sistema',
                'verbose_name_plural': 'usuarios do sistema',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('professor', models.CharField(max_length=120)),
                ('horario', models.CharField(blank=True, max_length=80)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='core.turma')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=100)),
                ('avaliacao', models.CharField(max_length=80)),
                ('valor', models.DecimalField(decimal_places=1, max_digits=4)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='core.usuariosistema')),
            ],
            options={
                'ordering': ['aluno__nome', 'disciplina'],
            },
        ),
    ]
