# Generated by Django 5.2.14 on 2026-05-19 21:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='postreaction',
            name='uniq_post_reaction',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('announcement', 'Aviso'), ('material', 'Material'), ('discussion', 'Discussao'), ('event', 'Evento')], default='discussion', max_length=20),
        ),
        migrations.AlterField(
            model_name='postreaction',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'Curtir'), ('love', 'Amei'), ('laugh', 'Achei engracado'), ('wow', 'Surpreso'), ('sad', 'Triste'), ('clap', 'Aplausos'), ('fire', 'Destaque')], default='like', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='postreaction',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='uniq_post_user_reaction'),
        ),
    ]
