# Generated by Codex on 2026-05-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagement", "0002_remove_postreaction_uniq_post_reaction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postreaction",
            name="reaction_type",
            field=models.CharField(
                choices=[("like", "Curtir")],
                default="like",
                max_length=20,
            ),
        ),
    ]
