# Generated by Django 5.2.14 on 2026-05-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('active', 'Ativa'), ('closed', 'Encerrada')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='observation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('submitted', 'Entregue'), ('late', 'Atrasada'), ('reviewed', 'Corrigida'), ('closed', 'Encerrada')], default='pending', max_length=20),
        ),
    ]
