# Generated by Django 5.2.14 on 2026-05-15 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=40)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('stage', models.CharField(choices=[('fundamental_i', 'Ensino Fundamental I'), ('fundamental_ii', 'Ensino Fundamental II'), ('high_school', 'Ensino Medio')], max_length=30)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['stage', 'sequence', 'name'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='term',
            field=models.CharField(choices=[('b1', '1o Bimestre'), ('b2', '2o Bimestre'), ('b3', '3o Bimestre'), ('b4', '4o Bimestre'), ('recovery', 'Recuperacao')], default='b1', max_length=20),
        ),
        migrations.AddField(
            model_name='classroom',
            name='shift',
            field=models.CharField(choices=[('morning', 'Manha'), ('afternoon', 'Tarde'), ('evening', 'Noite'), ('full_time', 'Integral')], default='morning', max_length=20),
        ),
        migrations.AddField(
            model_name='grade',
            name='term',
            field=models.CharField(choices=[('b1', '1o Bimestre'), ('b2', '2o Bimestre'), ('b3', '3o Bimestre'), ('b4', '4o Bimestre'), ('recovery', 'Recuperacao')], default='b1', max_length=20),
        ),
        migrations.AddField(
            model_name='classroom',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='grade_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='academics.gradelevel'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['shift', 'is_active'], name='academics_c_shift_30ccc3_idx'),
        ),
    ]
