# Generated by Django 5.2.14 on 2026-05-15 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_academicyear_gradelevel_attendance_term_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('monday', 'Segunda'), ('tuesday', 'Terca'), ('wednesday', 'Quarta'), ('thursday', 'Quinta'), ('friday', 'Sexta'), ('saturday', 'Sabado')], max_length=20)),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField()),
                ('room_label', models.CharField(blank=True, max_length=40)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='academics.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='academics.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['classroom', 'weekday', 'starts_at'],
                'indexes': [models.Index(fields=['classroom', 'weekday'], name='academics_w_classro_660365_idx'), models.Index(fields=['teacher', 'weekday'], name='academics_w_teacher_65c011_idx')],
                'constraints': [models.UniqueConstraint(fields=('classroom', 'weekday', 'starts_at'), name='uniq_schedule_slot_per_classroom')],
            },
        ),
    ]
