# Generated by Codex on 2026-05-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_weeklyschedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklyschedule",
            name="entry_type",
            field=models.CharField(
                choices=[("class", "Aula"), ("break", "Intervalo")],
                default="class",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="weeklyschedule",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weekly_schedules",
                to="academics.subject",
            ),
        ),
        migrations.AlterField(
            model_name="weeklyschedule",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "teacher"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weekly_schedules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
