# Generated by Django 5.2.14 on 2026-05-19 23:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_weeklyschedule_break_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='weeklyschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'CLASS')), fields=('teacher', 'weekday', 'starts_at'), name='uniq_teacher_slot_per_class'),
        ),
    ]
