# Generated by Django 5.2.14 on 2026-05-20 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_weeklyschedule_uniq_teacher_slot_per_class'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weeklyschedule',
            name='uniq_teacher_slot_per_class',
        ),
    ]
