# Generated by Django 5.2.15 on 2026-06-03 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_lesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absences', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academics.lesson')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['lesson', 'student'],
                'indexes': [models.Index(fields=['lesson', 'student'], name='academics_a_lesson__e54568_idx'), models.Index(fields=['student'], name='academics_a_student_f4c332_idx')],
                'constraints': [models.UniqueConstraint(fields=('lesson', 'student'), name='uniq_attendance_record_per_lesson_student')],
            },
        ),
    ]
