# Generated by Django 5.2.15 on 2026-06-03 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_attendancerecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('P1', 'P1'), ('REC1', 'REC1'), ('P2', 'P2'), ('REC2', 'REC2'), ('P3', 'P3'), ('REC3', 'REC3'), ('P4', 'P4'), ('REC4', 'REC4'), ('FINAL', 'FINAL')], max_length=10)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('quantidade_aulas', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.classroom')),
                ('professor', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.subject')),
            ],
            options={
                'ordering': ['-date', 'subject', 'assessment_type'],
            },
        ),
        migrations.CreateModel(
            name='GradeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_entries', to='academics.assessment')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='grade_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['assessment', 'student'],
            },
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['professor', 'classroom', 'subject', 'assessment_type'], name='academics_a_profess_06010d_idx'),
        ),
        migrations.AddIndex(
            model_name='gradeentry',
            index=models.Index(fields=['assessment', 'student'], name='academics_g_assessm_40a3e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='gradeentry',
            constraint=models.UniqueConstraint(fields=('assessment', 'student'), name='uniq_gradeentry_per_assessment_student'),
        ),
    ]
